- name: "Install Nginx"
  action: apt pkg={{ item }}
              state=latest
  with_items:
      - nginx

- name: "Install new default configuration file"
  template: src=nginx.conf.j2
      dest=/etc/nginx/nginx.conf
  notify:
      - restart nginx

# - name: "Symlink /opt/leaf-api/webroot => /var/www/.."
#   file: src={{ api_webroot }}
#         dest={{ apache_leaf_api_webroot }}
#         state=link
#   notify:
#       - restart apache
#
# - name: "Enable headers add-on"
#   command: a2enmod headers
#   notify:
#       restart apache
